import type {
  Customer,
  Complaint,
  EmailMessage,
  Notification,
  DateRange,
} from "./types";

// ─── Customer DB ──────────────────────────────────────────────────────────────
export const CUSTOMER_DB: Customer[] = [
  {
    id: "CUST-4421",
    name: "John Smith",
    email: "j.smith@email.com",
    mobile: "07700 900123",
    vehicles: ["AB12 XYZ", "DE45 RST"],
    postcode: "DE1 3AT",
  },
  {
    id: "CUST-3891",
    name: "Michael Brown",
    email: "m.brown@outlook.com",
    mobile: "07700 900789",
    vehicles: ["UV67 WXY"],
    postcode: "S1 2BQ",
  },
  {
    id: "CUST-2210",
    name: "Robert Davis",
    email: "r.davis@email.com",
    mobile: "07700 900654",
    vehicles: [],
    postcode: "LS1 4DW",
  },
  {
    id: "CUST-5103",
    name: "Amanda White",
    email: "a.white@gmail.com",
    mobile: "07700 900987",
    vehicles: ["CD34 MNO"],
    postcode: "M1 5EF",
  },
  {
    id: "CUST-1892",
    name: "Paul Martin",
    email: "p.martin@business.co.uk",
    mobile: "07700 900111",
    vehicles: ["EF56 PQR", "GH78 STU"],
    postcode: "DE1 2HG",
  },
  {
    id: "CUST-6201",
    name: "James Clarke",
    email: "j.clarke@email.com",
    mobile: "07700 900333",
    vehicles: ["JK90 VWX"],
    postcode: "S2 4LK",
  },
  {
    id: "CUST-6202",
    name: "Sarah Thompson",
    email: "s.thompson@gmail.com",
    mobile: "07700 900444",
    vehicles: ["LM12 YZA"],
    postcode: "LS2 7MN",
  },
  {
    id: "CUST-6203",
    name: "David Wilson",
    email: "d.wilson@outlook.com",
    mobile: "07700 900555",
    vehicles: ["NO34 BCD"],
    postcode: "M2 3PQ",
  },
  {
    id: "CUST-6204",
    name: "Emma Johnson",
    email: "e.johnson@email.com",
    mobile: "07700 900666",
    vehicles: [],
    postcode: "DE3 8RS",
  },
  {
    id: "CUST-6205",
    name: "Thomas Hughes",
    email: "t.hughes@business.co.uk",
    mobile: "07700 900777",
    vehicles: ["PQ56 EFG", "RS78 HIJ"],
    postcode: "S3 9TU",
  },
  {
    id: "CUST-6206",
    name: "Laura Mitchell",
    email: "l.mitchell@email.com",
    mobile: "07700 900888",
    vehicles: ["TU90 KLM"],
    postcode: "LS3 1VW",
  },
  {
    id: "CUST-6207",
    name: "Christopher Lee",
    email: "c.lee@outlook.com",
    mobile: "07700 900999",
    vehicles: ["VW12 NOP"],
    postcode: "M4 6XY",
  },
  {
    id: "CUST-6208",
    name: "Rachel Green",
    email: "r.green@gmail.com",
    mobile: "07700 901010",
    vehicles: ["XY34 QRS"],
    postcode: "DE4 2ZA",
  },
];

// ─── Dealer → Agent mapping ───────────────────────────────────────────────────
export const DEALER_AGENTS: Record<string, string[]> = {
  "Parkway Derby": ["Sarah Wilson", "Emma Clarke"],
  "Parkway Sheffield": ["James Patterson"],
  "Parkway Leeds": ["Emma Clarke", "David Hughes"],
  "Parkway Manchester": ["David Hughes", "Sarah Wilson"],
};

// ─── Email Threads ────────────────────────────────────────────────────────────
export const EMAIL_THREADS: Record<string, EmailMessage[]> = {
  "CC-1024": [
    {
      id: "em-3",
      isOutgoing: true,
      from: "Sarah Wilson <support@parkwayderby.co.uk>",
      to: "j.smith@email.com",
      subject: "Re: Complaint CC-1024 — Vehicle repair delay",
      date: "24 Jul 2026, 09:14",
      body: "Dear Mr Smith,\n\nThank you for your continued patience. I have spoken with the workshop manager and can confirm that the parts required are due to arrive tomorrow morning. We will prioritise your vehicle and aim to complete the work by end of day.\n\nPlease accept our sincere apologies for the delay.\n\nKind regards,\nSarah Wilson\nCustomer Relations Manager | Parkway Derby",
    },
    {
      id: "em-2",
      isOutgoing: false,
      from: "j.smith@email.com",
      to: "support@parkwayderby.co.uk",
      subject: "Re: Complaint CC-1024 — Vehicle repair delay",
      date: "22 Jul 2026, 18:30",
      body: "Good evening,\n\nI am still waiting for an update on my vehicle. It has been over a week and I have had no communication whatsoever. This is completely unacceptable.\n\nI expect someone to contact me first thing tomorrow morning.\n\nJohn Smith",
    },
    {
      id: "em-1",
      isOutgoing: true,
      from: "support@parkwayderby.co.uk",
      to: "j.smith@email.com",
      subject: "Your complaint has been registered — CC-1024",
      date: "20 Jul 2026, 15:25",
      body: "Dear Mr Smith,\n\nThank you for contacting Parkway Derby. This email confirms that your complaint has been registered with reference number CC-1024.\n\nA member of our team will be in touch within 2 business days.\n\nKind regards,\nCustomer Support Team\nParkway Derby",
    },
  ],
  "CC-1022": [
    {
      id: "em-2",
      isOutgoing: true,
      from: "Emma Clarke <support@parkwayderby.co.uk>",
      to: "m.brown@outlook.com",
      subject: "Re: Complaint CC-1022 — Unauthorised charge on invoice",
      date: "23 Jul 2026, 14:10",
      body: "Dear Mr Brown,\n\nThank you for contacting us. We have reviewed your invoice and note the £180 diagnostic charge. Could you please provide a copy of any written quote or confirmation you received prior to your service visit?\n\nKind regards,\nEmma Clarke\nCustomer Relations | Parkway Derby",
    },
    {
      id: "em-1",
      isOutgoing: false,
      from: "m.brown@outlook.com",
      to: "support@parkwayderby.co.uk",
      subject: "Complaint — Unauthorised charge on invoice",
      date: "18 Jul 2026, 10:10",
      body: "Good morning,\n\nI am writing to formally complain about an unauthorised charge of £180 for a diagnostic check on my service invoice dated 16 July 2026.\n\nI was not informed of or asked to authorise this additional work. I am requesting an immediate full refund.\n\nMichael Brown",
    },
  ],
};

// ─── Complaints Data ──────────────────────────────────────────────────────────
export const COMPLAINTS: Complaint[] = [
  {
    id: "CC-1024",
    status: "New",
    category: "Vehicle Quality",
    dealer: "Parkway Derby",
    vehicle: "AB12 XYZ",
    assignedTo: "Sarah Wilson",
    createdDays: 10,
    created: "20 Jul 2026",
    updated: "24 Jul 2026",
    source: "Inbound",
    customer: {
      name: "John Smith",
      email: "j.smith@email.com",
      mobile: "07700 900123",
    },
    subject: "Vehicle repair delay — brake pads and oil change",
    description:
      "Customer reports that their vehicle has been at the dealership for 10 days for a brake pad replacement and oil change. No communication has been received and the work has not been completed.",
    timeline: [
      {
        id: "t5",
        type: "email",
        author: "Sarah Wilson",
        timestamp: "24 Jul 2026, 09:14",
        text: "Follow-up email sent. Parts arriving tomorrow.",
        emailId: "CC-1024",
      },
      {
        id: "t4",
        type: "call",
        author: "Sarah Wilson",
        timestamp: "21 Jul 2026, 09:45",
        text: "Inbound call from customer. Customer frustrated, workshop unable to locate parts.",
      },
      {
        id: "t3",
        type: "email",
        author: "Sarah Wilson",
        timestamp: "20 Jul 2026, 15:25",
        text: "Auto-acknowledgement email sent to customer.",
        emailId: "CC-1024",
      },
      {
        id: "t2",
        type: "assigned",
        author: "James Patterson",
        timestamp: "20 Jul 2026, 15:22",
        text: "Assigned to Sarah Wilson.",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "20 Jul 2026, 15:10",
        text: "Complaint registered via customer portal.",
      },
    ],
  },
  {
    id: "CC-1023",
    status: "In Progress",
    category: "Service Quality",
    dealer: "Parkway Sheffield",
    vehicle: "GH22 KLM",
    assignedTo: "James Patterson",
    createdDays: 7,
    created: "17 Jul 2026",
    updated: "23 Jul 2026",
    source: "Inbound",
    customer: {
      name: "Emily Turner",
      email: "e.turner@webmail.com",
      mobile: "07700 900456",
    },
    subject: "Poor customer service during MOT appointment",
    description:
      "Customer reports being kept waiting for over 2 hours beyond the scheduled MOT appointment time with no updates provided by staff.",
    timeline: [
      {
        id: "t3",
        type: "call",
        author: "James Patterson",
        timestamp: "18 Jul 2026, 10:30",
        text: "Outbound call to customer. Apologised for wait time, investigating with service team.",
      },
      {
        id: "t2",
        type: "assigned",
        author: "System",
        timestamp: "17 Jul 2026, 11:05",
        text: "Assigned to James Patterson.",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "17 Jul 2026, 11:00",
        text: "Complaint registered via telephone.",
      },
    ],
  },
  {
    id: "CC-1022",
    status: "Awaiting Customer",
    category: "Billing",
    dealer: "Parkway Derby",
    vehicle: "UV67 WXY",
    assignedTo: "Emma Clarke",
    createdDays: 12,
    created: "13 Jul 2026",
    updated: "23 Jul 2026",
    source: "Online Booking",
    customer: {
      name: "Michael Brown",
      email: "m.brown@outlook.com",
      mobile: "07700 900789",
    },
    subject: "Unauthorised £180 diagnostic charge on invoice",
    description:
      "Customer disputes a £180 diagnostic charge on their service invoice, stating they were never informed of or asked to authorise this additional work.",
    timeline: [
      {
        id: "t2",
        type: "email",
        author: "Emma Clarke",
        timestamp: "23 Jul 2026, 14:10",
        text: "Requested supporting documentation from customer.",
        emailId: "CC-1022",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "13 Jul 2026, 09:00",
        text: "Complaint registered via email.",
      },
    ],
  },
  // {
  //   id: "CC-1021",
  //   status: "Pending",
  //   category: "Parts & Accessories",
  //   dealer: "Parkway Leeds",
  //   vehicle: "CD34 MNO",
  //   assignedTo: "David Hughes",
  //   createdDays: 5,
  //   created: "21 Jul 2026",
  //   updated: "22 Jul 2026",
  //   source: "Inbound",
  //   customer: {
  //     name: "Amanda White",
  //     email: "a.white@gmail.com",
  //     mobile: "07700 900987",
  //   },
  //   subject: "Non-OEM parts used without prior agreement",
  //   description:
  //     "Customer states that non-original manufacturer parts were fitted during a service without their knowledge or prior written agreement.",
  //   timeline: [
  //     {
  //       id: "t2",
  //       type: "assigned",
  //       author: "James Patterson",
  //       timestamp: "21 Jul 2026, 13:15",
  //       text: "Assigned to David Hughes.",
  //     },
  //     {
  //       id: "t1",
  //       type: "created",
  //       author: "System",
  //       timestamp: "21 Jul 2026, 13:00",
  //       text: "Complaint received via telephone.",
  //     },
  //   ],
  // },
  {
    id: "CC-1020",
    status: "Resolved",
    category: "Vehicle Quality",
    dealer: "Parkway Manchester",
    vehicle: "EF56 PQR",
    assignedTo: "Sarah Wilson",
    createdDays: 19,
    created: "5 Jul 2026",
    updated: "20 Jul 2026",
    source: "Inbound",
    customer: {
      name: "Paul Martin",
      email: "p.martin@business.co.uk",
      mobile: "07700 900111",
    },
    subject: "New damage found on vehicle after service",
    description:
      "Customer discovered a scratch on the driver-side door that was not present prior to a scheduled full service. Photographic check-in was not completed.",
    timeline: [
      {
        id: "t3",
        type: "status",
        author: "Sarah Wilson",
        timestamp: "20 Jul 2026, 16:00",
        text: "Status changed to Resolved. Paintwork repair completed. Customer satisfied.",
      },
      {
        id: "t2",
        type: "call",
        author: "Sarah Wilson",
        timestamp: "6 Jul 2026, 09:00",
        text: "Outbound call to customer. Damage confirmed. Agreed to paintwork rectification.",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "5 Jul 2026, 10:00",
        text: "Complaint registered.",
      },
    ],
  },
  {
    id: "CC-1019",
    status: "Closed",
    category: "Customer Experience",
    dealer: "Parkway Sheffield",
    vehicle: "GH78 STU",
    assignedTo: "James Patterson",
    createdDays: 25,
    created: "29 Jun 2026",
    updated: "15 Jul 2026",
    source: "Online Booking",
    customer: {
      name: "Karen Davies",
      email: "k.davies@email.co.uk",
      mobile: "07700 900222",
    },
    subject: "Rude behaviour from service reception staff",
    description:
      "Customer reports dismissive and disrespectful treatment from a member of the service reception team during a routine tyre change appointment.",
    timeline: [
      {
        id: "t4",
        type: "status",
        author: "James Patterson",
        timestamp: "15 Jul 2026, 15:00",
        text: "Status changed to Closed. Customer confirmed satisfaction. No further action required.",
      },
      {
        id: "t3",
        type: "status",
        author: "James Patterson",
        timestamp: "10 Jul 2026, 11:00",
        text: "Status changed to Resolved. Staff retraining scheduled.",
      },
      {
        id: "t2",
        type: "email",
        author: "James Patterson",
        timestamp: "30 Jun 2026, 09:00",
        text: "Formal apology sent to customer.",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "29 Jun 2026, 14:30",
        text: "Complaint received via online form.",
      },
    ],
  },
  {
    id: "CC-1018",
    status: "In Progress",
    category: "Warranty",
    dealer: "Parkway Leeds",
    vehicle: "IJ90 VWX",
    assignedTo: "Emma Clarke",
    createdDays: 18,
    created: "7 Jul 2026",
    updated: "21 Jul 2026",
    source: "Inbound",
    customer: {
      name: "Thomas Hall",
      email: "t.hall@enterprise.com",
      mobile: "07700 900333",
    },
    subject: "Warranty claim refused without adequate explanation",
    description:
      "Customer's warranty claim for a recurring engine fault was declined. Customer states the fault was reported within the warranty period and requests a formal review.",
    timeline: [
      {
        id: "t2",
        type: "note",
        author: "Emma Clarke",
        timestamp: "9 Jul 2026, 10:00",
        text: "Reviewed warranty documentation. Fault first reported 2 days before expiry. Escalating to warranty manager.",
      },
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "7 Jul 2026, 08:45",
        text: "Complaint escalated from service team.",
      },
    ],
  },
  {
    id: "CC-1017",
    status: "New",
    category: "Billing",
    dealer: "Parkway Manchester",
    vehicle: "KL12 YZA",
    assignedTo: "David Hughes",
    createdDays: 3,
    created: "23 Jul 2026",
    updated: "23 Jul 2026",
    source: "Inbound",
    customer: {
      name: "Sandra West",
      email: "s.west@mail.com",
      mobile: "07700 900444",
    },
    subject: "Overcharged on tyre replacement — invoice error",
    description:
      "Customer was charged for four premium tyres but only two were replaced. Invoice reflects £420 more than the agreed quote.",
    timeline: [
      {
        id: "t1",
        type: "created",
        author: "System",
        timestamp: "23 Jul 2026, 09:00",
        text: "Complaint received via telephone.",
      },
    ],
  },
];

// ─── Initial Notifications ────────────────────────────────────────────────────
export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "warning",
    title: "SLA Breach — CC-1018",
    body: "CC-1018 has exceeded the 14-day resolution target.",
    time: "2m ago",
    read: false,
    complaintId: "CC-1018",
  },
  {
    id: "n2",
    type: "info",
    title: "CC-1022 awaiting response",
    body: "No customer response received for 5 days.",
    time: "1h ago",
    read: false,
    complaintId: "CC-1022",
  },
  {
    id: "n3",
    type: "success",
    title: "CC-1020 resolved",
    body: "Paul Martin paintwork complaint resolved.",
    time: "4h ago",
    read: false,
    complaintId: "CC-1020",
  },
  {
    id: "n4",
    type: "warning",
    title: "CC-1017 not assigned",
    body: "New complaint has not been assigned to an agent.",
    time: "1d ago",
    read: true,
    complaintId: "CC-1017",
  },
  {
    id: "n5",
    type: "info",
    title: "New complaint received",
    body: "CC-1024 submitted via online portal.",
    time: "2d ago",
    read: true,
    complaintId: "CC-1024",
  },
  {
    id: "n6",
    type: "success",
    title: "CC-1019 closed",
    body: "Karen Davies complaint fully closed.",
    time: "3d ago",
    read: true,
    complaintId: "CC-1019",
  },
];
